# Yarn configuration file
nodeLinker: node-modules

# Enable zero-installs (optional, for better performance)
enableGlobalCache: true

# Use the same registry as npm
npmRegistryServer: "https://registry.npmjs.org/"

# Enable audit for security
enableAudit: true

# Disable fund messages
enableFund: false

# Enable progress bar
enableProgress: true

# Set engine strict mode
enableStrictSsl: true
